### ISSUE TITLE
Unintended consequences of router script install

### ISSUE THREAD

**Issue by rustjakey** [benisai/Openwrt-Monitoring#6]
First, thank you for the time you put into this. What I describe below is likely my lack of knowledge over anything. 

When I cloned, edited and ran the router script, shortly after the IP I had given as the server IP started showing up on devices as the gateway assigned DNS server. I am assuming this is how you manage to collect all the traffic data, by making the data collection server the DNS server. Anyway, this slowly broke my network as devices renewed their lease and the server IP became the DNS server and it did not function as a DNS server. 

I could not for the life of me change it in openwrt so had to wipe my router. 

I have not reinstalled as I do not really understand how the setup works well enough to prevent the whole thing happening again. 

The reason I post this is maybe it was not supposed to happen, and if it is the README could be updated to let people know it may happen (and remind people to backup before installing many packages, I forgot!)

Many thanks

**Comment by benisai** [comment]
I set the DNS on the interface level so Adguard home on my docker server can see the host name of each device. You are correct, if your docker server does not have adguard home for DNS, and it will cause impact to your network as DNS resolution will no longer work. 

But you can skip that part of the script by commenting it out. (I will actually comment that out of the script right now, it seems to be causing people headaches)
go to  Luci > Network > Interfaces > lan > DHCP Server > Advanced Settings > DHCP-Options >  and remove the IP,6. and reboot your OpenWRT router .

Otherwise, if you reset your router, You can rerun the script and it will not update the interface DNS. 

Sorry for the headaches. This is why I was a little hesitant to upload my scripts ;)
